# Generated by Django 4.0 on 2021-12-28 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, max_length=50)),
                ('language_code_iso', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('origin_country_iso', models.CharField(blank=True, choices=[('IR', 'Iran'), ('HU', 'Hungary'), ('AT', 'Austria'), ('DE', 'Germany'), ('GB', 'United Kingdom'), ('RS', 'Serbia'), ('BE', 'Belgium'), ('BA', 'Bosnia and Herzegovina'), ('CX', 'Christmas Island'), ('SE', 'Sweden'), ('CZ', 'Czechia'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('AU', 'Australia'), ('FK', 'Falkland Islands'), ('RO', 'Romania'), ('SI', 'Slovenia'), ('DK', 'Denmark'), ('CH', 'Switzerland'), ('IE', 'Ireland'), ('HR', 'Croatia'), ('PL', 'Poland'), ('LT', 'Lithuania'), ('CY', 'Cyprus'), ('BL', 'Saint Barthélemy'), ('FR', 'France'), ('DJ', 'Djibouti'), ('PT', 'Portugal'), ('US', 'United States'), ('AE', 'United Arab Emirates'), ('GD', 'Grenada'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('NO', 'Norway'), ('SG', 'Singapore'), ('LU', 'Luxembourg'), ('FI', 'Finland')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country_iso', models.CharField(blank=True, choices=[('IR', 'Iran'), ('HU', 'Hungary'), ('AT', 'Austria'), ('DE', 'Germany'), ('GB', 'United Kingdom'), ('RS', 'Serbia'), ('BE', 'Belgium'), ('BA', 'Bosnia and Herzegovina'), ('CX', 'Christmas Island'), ('SE', 'Sweden'), ('CZ', 'Czechia'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('AU', 'Australia'), ('FK', 'Falkland Islands'), ('RO', 'Romania'), ('SI', 'Slovenia'), ('DK', 'Denmark'), ('CH', 'Switzerland'), ('IE', 'Ireland'), ('HR', 'Croatia'), ('PL', 'Poland'), ('LT', 'Lithuania'), ('CY', 'Cyprus'), ('BL', 'Saint Barthélemy'), ('FR', 'France'), ('DJ', 'Djibouti'), ('PT', 'Portugal'), ('US', 'United States'), ('AE', 'United Arab Emirates'), ('GD', 'Grenada'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('NO', 'Norway'), ('SG', 'Singapore'), ('LU', 'Luxembourg'), ('FI', 'Finland')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Released', 'Released'), ('In Production', 'In Production')], max_length=25)),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('vote_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('runtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('budget', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('release_date', models.DateField()),
                ('overview', models.TextField(blank=True)),
                ('original_language_iso', models.CharField(max_length=2)),
                ('homepage', models.URLField()),
                ('adult', models.BooleanField(default=False)),
                ('tmdb_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('imdb_id', models.CharField(max_length=25)),
                ('poster_image', models.URLField()),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
                ('production_companies', models.ManyToManyField(related_name='movies', to='movies.ProductionCompanies')),
                ('production_counties', models.ManyToManyField(related_name='movies', to='movies.ProductionCountries')),
                ('spoken_languages', models.ManyToManyField(related_name='movies', to='movies.MovieLanguages')),
            ],
        ),
    ]
