# Generated by Django 4.0 on 2021-12-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieLanguages',
            new_name='MovieLanguage',
        ),
        migrations.RenameModel(
            old_name='ProductionCompanies',
            new_name='ProductionCompany',
        ),
        migrations.RenameModel(
            old_name='ProductionCountries',
            new_name='ProductionCountry',
        ),
    ]
