# Generated by Django 4.0 on 2021-12-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movielanguages_movielanguage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielanguage',
            old_name='language_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movielanguage',
            old_name='language_code_iso',
            new_name='origin_country',
        ),
        migrations.RenameField(
            model_name='productioncompany',
            old_name='origin_country_iso',
            new_name='origin_country',
        ),
        migrations.RenameField(
            model_name='productioncountry',
            old_name='origin_country_iso',
            new_name='origin_country',
        ),
    ]
