# Generated by Django 4.0 on 2021-12-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_language_name_movielanguage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='movielanguage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='origin_country',
            field=models.CharField(blank=True, choices=[('IR', 'Iran'), ('HU', 'Hungary'), ('AT', 'Austria'), ('DE', 'Germany'), ('GB', 'United Kingdom'), ('RS', 'Serbia'), ('BE', 'Belgium'), ('BA', 'Bosnia and Herzegovina'), ('CX', 'Christmas Island'), ('SE', 'Sweden'), ('CZ', 'Czechia'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('AU', 'Australia'), ('FK', 'Falkland Islands'), ('RO', 'Romania'), ('SI', 'Slovenia'), ('DK', 'Denmark'), ('CH', 'Switzerland'), ('IE', 'Ireland'), ('HR', 'Croatia'), ('PL', 'Poland'), ('LT', 'Lithuania'), ('CY', 'Cyprus'), ('BL', 'Saint Barthélemy'), ('FR', 'France'), ('DJ', 'Djibouti'), ('PT', 'Portugal'), ('US', 'United States'), ('AE', 'United Arab Emirates'), ('GD', 'Grenada'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('NO', 'Norway'), ('SG', 'Singapore'), ('LU', 'Luxembourg'), ('FI', 'Finland')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='productioncountry',
            name='origin_country',
            field=models.CharField(blank=True, choices=[('IR', 'Iran'), ('HU', 'Hungary'), ('AT', 'Austria'), ('DE', 'Germany'), ('GB', 'United Kingdom'), ('RS', 'Serbia'), ('BE', 'Belgium'), ('BA', 'Bosnia and Herzegovina'), ('CX', 'Christmas Island'), ('SE', 'Sweden'), ('CZ', 'Czechia'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('AU', 'Australia'), ('FK', 'Falkland Islands'), ('RO', 'Romania'), ('SI', 'Slovenia'), ('DK', 'Denmark'), ('CH', 'Switzerland'), ('IE', 'Ireland'), ('HR', 'Croatia'), ('PL', 'Poland'), ('LT', 'Lithuania'), ('CY', 'Cyprus'), ('BL', 'Saint Barthélemy'), ('FR', 'France'), ('DJ', 'Djibouti'), ('PT', 'Portugal'), ('US', 'United States'), ('AE', 'United Arab Emirates'), ('GD', 'Grenada'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('NO', 'Norway'), ('SG', 'Singapore'), ('LU', 'Luxembourg'), ('FI', 'Finland')], max_length=2, null=True),
        ),
    ]
