# Generated by Django 3.2 on 2021-12-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211230_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='production_counties',
            new_name='production_countries',
        ),
    ]
